//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public long Id { get; set; }
        public long Venta { get; set; }
        public long Libro { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Libro Libro1 { get; set; }
        public virtual Venta Venta1 { get; set; }
    }
}
